### ISSUE TITLE
운영체제 개발에 참고

### ISSUE THREAD

**Issue by minseo0388** [comjun04/StarOS#3]
소스가 매우 잘 짜여 있네요. 많은 모드도 지원하는 것이 좋은 것 같습니다.
제가 요즘 간단하게라도 운영체제를 만들어보고 있는데, 소스 코드를 참고하거나 일부 복사해도 됩니까?

1. 고등학교 1학년 국어교과서에 원 저작자에게 동의를 구하고, 구하더라도 출처를 밝혀야 한다. - 사회적 차원의 글쓰기 윤리
2. 고등학교 1학년 국어교과서에 질문의 형식을 사용함으로서 상대에게 선택지를 준다. - 공손성의 원리, 요령의 격률
3. 고등학교 1학년 국어교과서에 비난하는 표현은 줄이고, 칭찬하는 표현은 최대화한다. - 공손성의 원리, 찬동의 격률

을 준수하였습니다.

**Comment by comjun04** [comment]
저거 튜토리얼 보고 짠거라;;
쨌든 손 놓고 있던 지 시간이 많이 지나서 관리 안하고 있었는데
이렇게 이슈 달아줘서 감사합니다 (?)

네 참고 가능하고 일부 복사도 가능합니다
~~어차피 깃헙에 검색하면 이 코드의 대부분이 다른 사람이 쓴 코드입니다~~

@Naesung
